### ISSUE TITLE
Ideas 

### ISSUE THREAD

**Issue by cryogenian** [cryogenian/purescript-routing#1]
- Using `purescript-parsing` and provide basic parsers for querystrings etc
- Using parsers on `StrMap` constructed from hash
- Partial isomorphism on `String` or `StrMap` and `Route` 
- Provide templates for parsing? `/foo/:foo/bar/:bar` `foo=bar&bar=baz`

**Comment by cryogenian** [comment]
Router role in application
- `Routing` is global component governing all application. Application must be built on top of routing.
- `Routing` is just component, that can be used by other components in application. Components must listen router to handle changes

I would prefer to use global routing because we abandon idea of using components and even with components it's much simpler and more clean.

**Comment by cryogenian** [comment]
`onhashchange` provides stream of pairs `Tuple String String` where `fst` - old, `snd` - new. 
Assume we have `s` and this `s` is type of our application state. 
Variants of mapping 
- `snd -> s`
- `snd -> (s -> s)`
- `(fst -> snd) -> (s -> s)` 
  In case of `purescript-halogen` `s -> s` is `i`.

**Comment by cryogenian** [comment]
In fact there is no `fst -> snd` we have only `(fst, snd)` and 
we need not `s -> s` we need `Eff e (s -> s)`

``` purescript
parse :: Tuple String String -> Tuple (StrMap String) (StrMap String)
diff :: Tuple (StrMap String) (StrMap String) -> StrMap String
halogen :: StrMap String -> i
common :: StrMap String -> Eff e (s -> s) 
```

Why is there no any routers with explicit handling hash differences in js? 
All routers I found parse url and then fire callback with it. 
- They use implicit state, so `Eff e (s -> s)` degenerate to `Eff e Unit` 
- They follow server pattern, and **HTTP** is stateless → `diff (Tuple _ a) = a`

**Comment by cryogenian** [comment]
Suppose we were `foo.com#bar/1,2,3/baz/2,3` and then go to `foo.com#bar/1,2,3/baz/1,2` 
If coming to `bar/1,2,3` make ajax to `api.foo.com?bar=1,2,3` and if coming to `baz/2,3` make ajax to `api.foo.com?baz=2,3`. So, when we have both we make two ajax and then making something in app. 

Question is how can we make without calculating `diff` make only one ajax in first example, and two when we go from `foo.com` to `foo.com#bar/1,2,3/baz/1,2`
1. go to `foo.com#bar/1,2,3/update/baz/1,2/` and make rewrite after getting ajax response 
2. make `/bar/1,2,3` parent of `/bar/1,2,3/baz/1,2` in general build route hierarchy

**Comment by garyb** [comment]
I also think global routing makes more sense, especially when integrating with halogen

I've never used a router that does diffing either. When using Bacon I tend to have a stream which has the URL hash split into segments, and then derive new streams from that by filtering, dropping from the head, reading from a specific index (and so on), and when one of those stream values is used to build a request, duplicates are dropped at that point. I guess that explicit duplicate value check is what you're trying to avoid?

It seems to me that usually it's just some portion of the tail of the URL changes, like I don't think I've ever had a URL scheme where I'd go from `/a/b/c` to `/a/x/c` - and even if that were to happen the `c` value would probably "mean" something different under `x` than it does under `b`... I'm not sure if that makes things any easier.

I'm not sure I entirely follow your last set of examples, sorry.

**Comment by garyb** [comment]
Should we have the option take advantage of `pushState` also?

**Comment by cryogenian** [comment]
@garyb I think that history api can be useful in some cases, but would prefer to integrate history api in next releases. 

I've decided to stick with hierarchy of routes.
