### ISSUE TITLE
another approach

### ISSUE THREAD

**Issue by cryogenian** [cryogenian/purescript-routing#2]
This is issue to aggregate my thoughts about @paf31 approach, described in my pr.

**Comment by cryogenian** [comment]
- I don't really understand what is the `Route` type, it seems that `Route` is just `String`, because we can't produce anything from hash until we define route matchers. (i.e. how can one to decide what is variables here `#foo/bar/baz/:12/++/bool` it's just string) 
- My elements: `Template()`, `RouteDiff`, `Route()` and `RouteMatch` for untyped. 
- Suggested: `Match`, `MatchImpl()`, probably `Route()` and `E`

Main differences are 
- AST representation. `Template` type and `Match` typeclass 
- Constrainted areas. There is significantly lesser number of instances in current code.

**Comment by paf31** [comment]
The main difference is that you seem to parse a template string into a template, and then produce a parser from it. What I'm suggesting is to define the templates in code, and to define two separate interpreters: one to output template strings, and one to generate matching functions. As I said on Skype, I didn't get the original requirements, so I didn't understand the need for the template strings. If they're just for documentation, it seems to make sense to generate them, not parse them.

`Route` is just a representation of the string in the hash, e.g. `/foo/1/bar/2/?baz=3` might be `Route [Lit "foo", Var "1", Lit "bar", Var "2"] [Tuple "baz" "3"]`. You could think of `String -> Route` as the lexing stage if you like.

**Comment by cryogenian** [comment]
But how can I know that `/foo/bar/bar2/` would interpret to `Route [Lit "foo", Var "bar", Lit "bar", Var "2"]? 
Everything could be a`Lit`or`Var`.

**Comment by paf31** [comment]
Yes, sorry, very good point :)

So `Route` would have to represent the first part as a `List String` essentially, and a `List (Tuple String String)` for the parameters.

The approach should still work though.

**Comment by cryogenian** [comment]
Yep, it should work :)

**Comment by cryogenian** [comment]
- Coded something. Got the point about errors, and why I should care in this case.
- `Bind` is useful to make functions like `num` or `bool` 
- Can't figure out how to make `forall a. (forall f. (Match f) => f a) -> Route -> Either String a`. `f a` is interpreter, it can completely forget type `a` in example. Moreover it can mean anything not restricted to routes and error handling. 
- found useful `fail` in `Match` (since match can fail and can have message about it)
